const sellers = [
    {
        firstName: "Michael James",
        lastName: "Altman",
        email: "mjaltman@reredirect.com",
        password: "mjaltman2325",
        category: "seller",
    },
    {
        firstName: "Robert",
        lastName: "Chapman",
        email: "rchapman@reredirect.com",
        password: "rchapman2528",
        category: "seller",
    },
    {
        firstName: "Beth",
        lastName: "Au",
        email: "bau@reredirect.com",
        password: "bau2325",
        category: "seller",
    },
    {
        firstName: "Elora",
        lastName: "Broyles",
        email: "ebroyles@reredirect.com",
        password: "ebroyles326",
        category: "seller",
    },
    {
        firstName: "John Randy",
        lastName: "Caldwell",
        email: "jrcaldwell@reredirect.com",
        password: "jrcaldwell5307",
        category: "seller",
    },
    {
        firstName: "Sharon",
        lastName: "Street-Caldwell",
        email: "sstreetcaldwell@reredirect.com",
        password: "sstreetcaldwell5307",
        category: "seller",
    },
    {
        firstName: "Jimmie Fielding",
        lastName: "Benton",
        email: "jfbenton@reredirect.com",
        password: "jfbenton2710",
        category: "seller",
    },
    {
        firstName: "Mi Ok",
        lastName: "Benton",
        email: "mobenton@reredirect.com",
        password: "mobenton2710",
        category: "seller",
    },
    {
        firstName: "Maria",
        lastName: "Chenes",
        email: "mchenes@reredirect.com",
        password: "mchenes1325",
        category: "seller",
    },
    {
        firstName: "Jae Young",
        lastName: "Ahn-Benton",
        email: "jyahnbenton@reredirect.com",
        password: "jyahnbenton6684",
        category: "seller",
    },
    {
        firstName: "Maria",
        lastName: "Kolesnyk",
        email: "mkolesnyk@reredirect.com",
        password: "mkolesnyk6684",
        category: "seller",
    },
    {
        firstName: "Valinda",
        lastName: "Williams",
        email: "vwilliams@reredirect.com",
        password: "vwilliams30",
        category: "seller",
    },
    {
        firstName: "Moon-Soo",
        lastName: "Tscha",
        email: "mstscha@reredirect.com",
        password: "mstscha11070",
        category: "seller",
    },
    {
        firstName: "Hyo Ok",
        lastName: "Lee",
        email: "holee@reredirect.com",
        password: "holee11070",
        category: "seller",
    },
    {
        firstName: "Elora Merry",
        lastName: "Paik",
        email: "empaik@reredirect.com",
        password: "empaik1943",
        category: "seller",
    },
    {
        firstName: "Tatiana",
        lastName: "Medins",
        email: "tmedins@reredirect.com",
        password: "tmedins5169",
        category: "seller",
    },
    {
        firstName: "Luana",
        lastName: "DeVol",
        email: "ldevol@reredirect.com",
        password: "ldevol1908",
        category: "seller",
    },
    {
        firstName: "Garrett",
        lastName: "McKeeman",
        email: "gmckeeman@reredirect.com",
        password: "gmckeeman2000",
        category: "seller",
    },
    {
        firstName: "Debra",
        lastName: "McKeeman",
        email: "dmckeeman@reredirect.com",
        password: "dmckeeman2000",
        category: "seller",
    },
    {
        firstName: "Aaron",
        lastName: "Janushan",
        email: "ajanushan@reredirect.com",
        password: "ajanushan7348",
        category: "seller",
    },
    {
        firstName: "Troy",
        lastName: "Hart",
        email: "thart@reredirect.com",
        password: "thart358",
        category: "seller",
    },
    {
        firstName: "Judith",
        lastName: "Mata",
        email: "jmata@reredirect.com",
        password: "jmata358",
        category: "seller",
    },
    {
        firstName: "Carolina Melody",
        lastName: "Guthrie",
        email: "cmguthrie@reredirect.com",
        password: "cmguthrie3975",
        category: "seller",
    },
    {
        firstName: "Steven",
        lastName: "Chenes",
        email: "schenes@reredirect.com",
        password: "schenes4241",
        category: "seller",
    },
    {
        firstName: "Don",
        lastName: "Forman",
        email: "dforman@reredirect.com",
        password: "dforman5140",
        category: "seller",
    },
    {
        firstName: "Lorie",
        lastName: "Forman",
        email: "lforman@reredirect.com",
        password: "lforman5140",
        category: "seller",
    },
    {
        firstName: "Ivan",
        lastName: "Ivanov",
        email: "iivanov@reredirect.com",
        password: "iivanov3647",
        category: "seller",
    },
    {
        firstName: "Matthew",
        lastName: "Herndon",
        email: "mherndon@reredirect.com",
        password: "mherndon4923",
        category: "seller",
    },
]

//export seed data to models/index.js
module.exports = sellers;